[package]
name = "grss"
version = "0.1.0"
edition = "2021"
readme = "README.md"
repository = "git."
license = "MIT"
[dependencies]
clap = {version = "4.0", features = ["derive"]}
anyhow = "1.0"
indicatif = "0.17.8"
env_logger = "0.11.15"
log = "0.4"
ctrlc = "3.4"
